# Generated by Django 3.2.10 on 2022-01-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockcrawer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='', max_length=50)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('days', models.IntegerField(blank=True, default='')),
            ],
        ),
    ]
